create table if not exists hardware (
    id int generated by default as identity (start with 4) primary key,
    name varchar(50) not null,
    code varchar(10) not null,
    price number not null,
    type varchar(8) not null,
    stock number not null,
    primary key(id)
);

create table if not exists review (
    id int generated by default as identity (start with 5) primary key,
    title varchar(50) not null,
    text varchar(255) not null,
    rating int not null,
    primary key(id),
    hardware_id int,
    constraint fk_hardware foreign key (hardware_id) references hardware(id) on delete cascade
);

create table if not exists users (
    id int generated by default as identity (start with 3) primary key,
    username varchar(50) not null unique,
    password varchar(1000) not null
);

create table if not exists authority (
    id int generated by default as identity (start with 3) primary key,
    authority_name varchar(100) not null unique
);

create table if not exists users_authority (
    user_id int not null,
    authority_id int not null,
    constraint fk_user foreign key (user_id) references users(id) on delete cascade,
    constraint fk_authority foreign key (authority_id) references  authority(id) on delete cascade
);